/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Used for initial authentication
         * @description This endpoint is used for initial authentication. Provides access token in response to userName+password
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/refreshToken": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Use refresh token to get a new token
         * @description When an access token is no longer valid, call this endpoint with the access token in the Authorization header
         *     and the refresh token in the json body. If the refresh token is still valid, a new token set will be returned.
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accessRequest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ensure that the user has a current 'access request code' and return it
         * @description A user can be granted access to a company by having an 'access request code' generated. Such a code can then
         *     be used by another user to grant request access. The 'access request code' is communicated between the users
         *     via another form of trusted communication (e.g. phone) for security reasons.
         */
        post: operations["accessRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Invalidate/expire tokens
         * @description Use this to invalidate or expire tokens. This allows a user to invalidate all tokens for security purposes,
         *     and it can be used by developers to test scenarios that would otherwise be difficult to test.
         */
        delete: operations["invalidateOrExpireTokens"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Provides user related information such as name, initials and administration
         * @description Will typically be called after login, but not required. If used, a call should be made periodically - e.g. when
         *     a mobile app is brought to the foreground
         */
        get: operations["getBaseUserInformation"];
        put?: never;
        /**
         * Creates a new user
         * @description Creating a new user - initially without access to any companies
         */
        post: operations["createUser"];
        /**
         * Deletes a user account
         * @description Deletes the user account associated with the provided token. This makes it possible to both sign up and remove the created account using the api
         */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List of companies the user has access to
         * @description This returns the list of companies that the user has access to. Can be empty.
         *     Importantly, this endpoint provides a 'companyXid' for each company and the 'companyXid' is
         *     used to identify the target company for most of the endpoints in this API.
         */
        get: operations["companies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/archiveFiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List of files in the document archive
         * @description This provides id, names, etc. for a selected list of documents in the document archive. Can be empty.
         */
        get: operations["archiveFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/archiveFile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch data for one specified archive file
         * @description This provides binary content as well as metadata for a specified file in the document archive.
         */
        get: operations["archiveFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/archiveFile/{companyXid}/{archiveFileXid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update archive file
         * @description Use this to update an archive file (date, name, etc.). The binary file itself cannot be updated
         */
        put: operations["updateArchiveFile"];
        post?: never;
        /**
         * Delete archive file
         * @description Use this to delete an archive file. The call will fail if the archive file is delete-protected (e.g. being
         *     referenced from a registration)
         */
        delete: operations["deleteArchiveFile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/filesForUseInRegistrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload file to be used in subsequent call to create a registration
         * @description To create a 'suggested registration' with one or more files attached, those files must first be uploaded to
         *     Multi-Regnskab using this endpoint. An identification is returned and that identification is then included in
         *     the 'filesToAttachXids' array in the call to /suggestedRegistrations.
         */
        post: operations["uploadFileForRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suggestedRegistrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create suggested registration that will be pending accept by user in Multi-Regnskab
         * @description TODO
         */
        post: operations["createSuggestedRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{companyXid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List of customers (used in invoicing)
         * @description This provides data for the list of customers in a company
         */
        get: operations["customers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new customer
         * @description Allows for basic creation of a new customer
         */
        post: operations["createCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new offer/invoice/credit-note (draft)
         * @description Typically used for basic creation of an outgoing invoice, but also allows for creation of offers and
         *     credit notes. After creation, it will exist in draft mode. This is early access which does not apply
         *     payment terms, etc. from customer. Also requires a product type to exist and a range of validations
         *     are missing. Introduced later February 2026
         */
        post: operations["createInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * BETA access. Register a sales transaction (that may not be completed) and possibly generate QR code
         * @description This is intended for registering a sale in a point-of-sales situation. The sale may not actually be completed.
         *     The information can feed an invoice but is otherwise used to generate a Mobiles QR code and track the likely
         *     MobilePay payment.
         */
        post: operations["createSales"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bankAccounts/{companyXid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Provides list of configured bank accounts in the specified company
         * @description Typical use is to get bankAccountXid's for bankAccounts with the purpose of subsequently
         *     calling bankPostings.
         */
        get: operations["bankAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bankPostings/{companyXid}/{bankAccountXid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch bank postings for a particular bank account
         * @description Gives you a list of bank postings that has been imported into Multi-Regnskab for bank reconciliation.
         *     Note that this endpoint only returns what has already been imported. No call is made to made to actually
         *     fetch recent postings via PSD2 integration or similar.
         */
        get: operations["bankPostings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bankBalances/{companyXid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Returns a list of the latest bank balances
         * @description Use of this endpoint requires an agreement where Multi-Regnskab daily (and automatically) fetches
         *     the current bank balances of all bank accounts configured in the company
         */
        get: operations["bankBalances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/productTypes/{companyXid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List of available product types in the specified company
         * @description Product types control finance bookings and vat for invoice lines. Each invoice line requires a
         *     product type which is identified by a productTypeXid
         */
        get: operations["productTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{companyXid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List of products in the specified company
         * @description A product can (but need not) be applied on lines of outgoing sales invoices.
         *     A product is identifier by a productXid
         */
        get: operations["products"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/unitsOfMeasure/{language}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List of available units of measure  (used on invoice lines)
         * @description E.g. EA for what would be 'stk.' in Danish.
         */
        get: operations["unitsOfMeasure"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            /** @example info@multiregnskab.dk */
            userName: string;
            password: string;
        };
        RefreshTokenRequest: {
            refreshToken: string;
        };
        CreateUserResponse: {
            tokenResponse: components["schemas"]["TokenResponse"];
            /** @example ABC123 */
            codeForAccessRequest: string;
        };
        TokenResponse: {
            token: string;
            /** @example 2021-09-27T23:59:59.999 */
            tokenExpires: string;
            refreshToken: string;
        };
        InvalidateOrExpireTokensRequest: {
            applyToAllTokensByUser: boolean;
            invalidateNow: boolean;
            expireAccessTokenNow: boolean;
            expireRefreshTokenNow: boolean;
        };
        InvalidateOrExpireTokensResponse: {
            /** Format: int32 */
            tokensAffected: number;
        };
        AccessRequestResponse: {
            /** @example ABC123 */
            accessRequestCode: string;
        };
        BaseUserData: {
            /** @example info@multiregnskab.dk */
            userName?: string;
            /** @example Peter Petersen */
            realName?: string;
            /**
             * Format: int64
             * @example 123456789
             */
            administratorXid?: number;
            /** @example Regnskabsmesteren */
            administratorName?: string;
            /** @example SUPER_USER */
            administratorRole?: string;
        };
        CreateUserRequest: {
            /**
             * @description e-mail address that will be used as user name. Will be lowercased. Max 70 chars.
             * @example info@multiregnskab.dk
             */
            userName: string;
            /** @description Password must be provided in plain text here but will be "salted" and "hashed" */
            password: string;
        };
        Registration: {
            /**
             * Format: int64
             * @description Xid of company that the registration belongs to
             * @example 123456
             */
            companyXid: number;
            /** @example 2021-12-31 */
            date: string;
            description: string;
            /**
             * Format: int64
             * @example 123456789
             */
            supplierXid?: number;
            /**
             * Format: int64
             * @example 123456789
             */
            customerXid?: number;
            /** @description Lines with finance account, vat and amount */
            debitCreditlines?: components["schemas"]["DebitCreditLine"][];
            /** @description References to files. Maximum number is 3 */
            filesToAttachXids?: components["schemas"]["EntityIdentification"][];
        };
        CompaniesAndAccess: {
            /** @description Company ids, names and access information */
            companiesAndAccessList: components["schemas"]["CompanyAndAccess"][];
            /**
             * @description Company xId's of the last companies accessed by the user. Client application should typically 'select' the
             *     first company in the array and if the array is empty select the first entry in companiesAndAccessList. Note
             *     that both arrays will be empty if the user has not been granted access to any companies.
             */
            lastCompanies: number[];
        };
        CompanyAndAccess: {
            /**
             * Format: int64
             * @example 123456789
             */
            xid: number;
            /** @example My Company ApS */
            name: string;
            /** @example 11223344 */
            cvr: string;
            allowDocumentsAdd: boolean;
            allowDocumentsEdit: boolean;
            allowDocumentsView: boolean;
        };
        EntityIdentification: {
            /**
             * Format: int64
             * @example 123456789
             */
            xid: number;
        };
        DebitCreditLine: {
            /** @example 3020 */
            accountNumber: string;
            /** @example DKI25 */
            vatCode?: string;
            /** @example 9.999,99 */
            amount: string;
        };
        ArchiveFiles: {
            /** @description Company ids, names and access information */
            archiveFilesList: components["schemas"]["ArchiveFileLine"][];
            /** @description if the number of files exceeds maxLines from request a continuation token is provided for a new request */
            continuationToken?: string;
        };
        ArchiveFileLine: {
            /**
             * Format: int64
             * @example 123456789
             */
            xid: number;
            /**
             * Format: int64
             * @example 123456789
             */
            id: number;
            /** @example 2021-12-31 */
            date?: string;
            /** @example Receipt from 7-eleven */
            name?: string;
            /**
             * @description Timestamp (CET timezone)
             * @example 2021-12-31T15:30:00.000
             */
            timestampLastUpdate?: string;
        };
        ArchiveFile: {
            /**
             * Format: int64
             * @description Xid of company that the file belongs to
             * @example 123456
             */
            companyXid: number;
            /**
             * Format: int64
             * @description Xid of the file
             * @example 123456
             */
            archiveFileXid: number;
            /** @description Base64 encoded file contents */
            fileBodyBase64: string;
            /** @description Optional plain text version of the file */
            plainText?: string;
            /** @description E.g. 'application/pdf', 'image/png', etc. */
            contentType: string;
            /** @description A file name typically having a suffix such as .pdf or .png */
            fileName: string;
            /** @description A (possibly) 'user friendly' name for the file */
            friendlyFilename: string;
            /**
             * @description The date associated with the file
             * @example 2021-12-31
             */
            date: string;
            einvoice?: components["schemas"]["Einvoice"];
            /** @description User-provided comments about the file */
            comments?: components["schemas"]["ArchiveFileComment"][];
        };
        ArchiveFileComment: {
            /**
             * @description The timestamp associated with the comment (CET timezone)
             * @example 2022-03-31T15:26:53.970
             */
            dateTime: string;
            /** @description The username of the author of the comment */
            userName: string;
            /** @description The real name of the author of the comment. Note that this can be null */
            realName?: string;
            /** @description Best effort initials. Note that this can be null */
            userInitials?: string;
            /** @description A comment about the file */
            comment: string;
        };
        Einvoice: {
            invoice: boolean;
            creditNote: boolean;
            number: string;
            documentDate: string;
            deliveryDate?: string;
            orderReferenceId?: string;
            note?: string;
            dueDate?: string;
            currency: string;
            exclVatAmount: string;
            vatBasisAmount: string;
            vatAmount: string;
            inclVatAmount: string;
            usesApplicationResponse?: boolean;
            acceptedApplicationResponseSent: boolean;
            rejectedApplicationResponseSent: boolean;
            accountingSupplier: components["schemas"]["EinvoiceParty"];
            accountingCustomer: components["schemas"]["EinvoiceParty"];
            lines: components["schemas"]["EinvoiceLine"][];
            paymentMeans: components["schemas"]["EinvoicePaymentMeans"][];
            additionalDocuments: components["schemas"]["EinvoiceAdditionalDocument"][];
        };
        EinvoicePaymentMeans: {
            paymentChannelType: string;
            paymentChannelDescription: string;
            paymentDueDate: string;
            paymentNote?: string;
            branchNumber?: string;
            accountNumber?: string;
            instructionId?: string;
            paymentId?: string;
            creditAccountAccountId?: string;
        };
        EinvoiceAdditionalDocument: {
            index: number;
            name: string;
            fileAttachment: boolean;
            mimeCode?: string;
        };
        EinvoiceParty: {
            name: string;
            legalEntityIdentifier?: string;
            endpointScheme: string;
            endpointId: string;
            addressFormatCode: string;
            streetName: string;
            buildingNumber?: string;
            cityName: string;
            postalZone: string;
            countryCode: string;
            contact?: string;
        };
        EinvoiceLine: {
            id: string;
            itemName: string;
            unitCode: string;
            quantity: string;
            itemPrice: string;
            lineExtensionAmount: string;
            note?: string;
            taxSchemeName?: string;
            taxPercent?: string;
            taxAmount?: string;
        };
        ArchiveFileUpdate: {
            /**
             * @description The date associated with the file. ISO 8601
             * @example 2021-12-31
             */
            date: string;
            /** @description A 'user friendly' name for the file */
            friendlyFilename: string;
            /** @description A new comment with notes about the file contents. If not adding new comment then provide null value */
            comment?: string;
        };
        FileUpload: {
            /**
             * Format: int64
             * @description Xid of company that the file should be stored for
             * @example 123456
             */
            companyXid: number;
            /** @description base64 encoded file contents */
            fileBodyBase64: string;
            /** @description E.g. 'application/pdf', 'image/png', etc. */
            contentType?: string;
            /** @description A file name typically having a suffix such as .pdf or .png. If no fileName is provided, one will be assigned server-side */
            fileName?: string;
            /** @description A 'friendly' file name can be provided so while fileName could easily be something like IMG001234.PNG, friendlyFileName could be 'Bakery receipt' */
            friendlyFilename?: string;
            /**
             * @description If no date is provided, the file will get 'todays date'. Use ISO 8601
             * @example 2021-12-31
             */
            date?: string;
            /**
             * @description By default, the file will not be visible to users until referenced when creating a new registration. Set to false to make the file appear in the inbox.
             * @default true
             */
            keepHiddenUntilRegistration: boolean;
            /** @description Provides a way for the user to add an initial comment to the file */
            comment?: string;
            /** @description Result of text recognition performed client side */
            recognizedTextElements?: components["schemas"]["RecognizedText"][];
        };
        RecognizedText: {
            /**
             * Format: double
             * @description x position of recognized text (increases from left to right)
             */
            xPosition: number;
            /**
             * Format: double
             * @description y position of recognized text (increases from bottom to top)
             */
            yPosition: number;
            /**
             * Format: double
             * @description width of bounding box
             */
            width?: number;
            /**
             * Format: double
             * @description height of bounding box
             */
            height?: number;
            /**
             * Format: float
             * @description Confidence of text recognition (0 to 1)
             */
            confidence?: number;
            /** @description Recognized text */
            text: string;
        };
        CustomerList: {
            customers?: components["schemas"]["Customer"][];
        };
        Customer: {
            /**
             * Format: int64
             * @example 123456789
             */
            companyXid: number;
            /**
             * Format: int64
             * @example 234567890
             */
            xid: number;
            /**
             * Format: int64
             * @example 345678901
             */
            entityVersion: number;
            customerName: string;
            customerNumber?: string;
            /** @description true for private customer - false for business customers */
            privatePerson?: boolean;
            /** @description E.g. CVR number for Danish business customers */
            companyIdentifier?: string;
            address1: string;
            address2?: string;
            address3?: string;
            zipCode: string;
            city: string;
            /** @example DK */
            countryCode: string;
            phone?: string;
            /** @description Attention person when invoicing */
            invoiceAtt?: string;
            /** @description Default e-mail recipient for invoices */
            invoiceEmail?: string;
            /** @example DKK */
            currencyCode: string;
            /**
             * @description LanguageCode that determines language on invoices and in e-mails
             * @example DA
             */
            languageCode: components["schemas"]["LanguageCode"];
            paymentTermsType: components["schemas"]["PaymentTermsType"];
            /**
             * Format: int
             * @example 20
             */
            paymentTermsDays?: number;
            /** @description Set true if customer is to receive e-invoices */
            electronicInvoice?: boolean;
            /** @description Required if electronicInvoice is true */
            electronicInvoiceDestinationType?: components["schemas"]["ElectronicInvoiceDestinationType"];
            /** @description Required if electronicInvoice is true */
            electronicInvoiceAddress?: string;
        };
        Invoice: {
            /**
             * Format: int64
             * @example 123456789
             */
            companyXid: number;
            /**
             * Format: int64
             * @description Identification of the invoice. Provide the value zero for new invoices.
             * @example 123456789
             */
            invoiceXid: number;
            /**
             * Format: int64
             * @description Identication of the invoice recipient
             * @example 123456789
             */
            customerXid: number;
            /**
             * @description The effective invoice date. When crating an invoice, this value must represent a value within a open fiscal year
             * @example 2026-01-31
             */
            date?: string;
            /** @example Assistance in January 2026 */
            title?: string;
            /** @default false */
            creditNote: boolean;
            /** @default false */
            offer: boolean;
            /** @default false */
            linesHaveProductId: boolean;
            /** @default false */
            linesHaveNumberAndPriceEach: boolean;
            /**
             * @description Will determine whether to show 'reverse charge' on the invoice
             * @default false
             */
            reverseCharge: boolean;
            lines: components["schemas"]["InvoiceLine"][];
        };
        InvoiceLine: {
            /**
             * Format: int32
             * @description Determines sorting of lines. Start with 0
             * @example 1
             */
            lineNo: number;
            /**
             * Format: int64
             * @description Optional reference to product. When creating an invoice line the following attributes will be set from
             *     the product: productTypeXid, lineText, unitOfMeasureCode, priceEach.
             *     Also, amount will be set as priceEach * numberOfUnits
             * @example 123456789
             */
            productXid?: number;
            /** @description Item text */
            lineText: string;
            /** @description More detailed description for the line item */
            lineNote?: string;
            /**
             * @description Number of items sold
             * @example 100 or 1.200,5
             */
            numberOfUnits?: string;
            /**
             * @description Unit of measure related to numberOfUnits. See list returned by /unitsOfMeasure for valid values
             * @example EA
             */
            unitOfMeasureCode?: string;
            /**
             * @description The price of each 'unit'. Multiply numberOfUnits with this to get line amount
             * @example 33,95
             */
            priceEach?: string;
            /**
             * @description Amount for the line (before possible VAT)
             * @example 3.35,00
             */
            amount: string;
            /**
             * Format: int64
             * @description Identification of the product type for the invoice line. It is required for determining finance booking
             *     and application of VAT
             * @example 123456789
             */
            productTypeXid: number;
        };
        SalesRequest: {
            /**
             * Format: int64
             * @example 123456789
             */
            companyXid: number;
            /**
             * Format: int64
             * @example 123456789
             */
            customerXid: number;
            /**
             * @description The amount (including vat if applied)
             * @example 9.999,99
             */
            amount: string;
            /**
             * @description Optional comment for own reference
             * @example Changed address to Bygaden 1
             */
            comment?: string;
            /**
             * @description Set true to have the response include a MobilePay QR code
             * @default false
             */
            generateMobilePayQrCode: boolean;
        };
        SalesResponse: {
            /**
             * Format: int64
             * @description Xid of company that the sale belongs to
             * @example 123456
             */
            companyXid: number;
            /**
             * Format: int64
             * @description Xid of the sale
             * @example 123456
             */
            saleXid: number;
            /** @description Base64 encoded QR code */
            qrCodeBase64: string;
        };
        /** @description A list of bank balances */
        BankBalances: {
            /** @description List of bank balances */
            bbList: components["schemas"]["BankBalance"][];
        };
        /**
         * @description A bank balance reflects the amount available on a given bank account at a specific time.
         *     There are different types of balances available with names such as 'ITAV' (Interim available),
         *     'ITBD' (Interim Booked) and 'FWAV' (Forward Available). This relates to questions such as
         *     'should the balance include a credit facility on the account' and 'should the balance include
         *     or exclude committed future transactions'.
         */
        BankBalance: {
            /**
             * Format: int64
             * @description Identification of the bank account in Multi-Regnskab
             * @example 333444555
             */
            bankAccountXid: number;
            /**
             * @description Name of the bank account in Multi-Regnskab
             * @example Main bank DKK
             */
            bankAccountName: string;
            /**
             * @description The balance type (see endpoint description)
             * @example ITAV
             */
            balanceType: string;
            /**
             * @description Bank account identification (Danish)
             * @example 99992222333344
             */
            bban?: string;
            /**
             * @description Bank account identification (International)
             * @example DK5000400440116243
             */
            iban?: string;
            /**
             * @description The amount
             * @example 9.999,99
             */
            balanceAmount: string;
            /**
             * @description Currency code
             * @example DKK
             */
            currency: string;
            /**
             * @description The time the balance was fetched from the bank (CET timezone)
             * @example 2026-03-05T15:30:00.000
             */
            timestamp?: string;
        };
        /** @description A list of product types */
        ProductTypes: {
            /** @description List of product types */
            ptList: components["schemas"]["ProductType"][];
        };
        /**
         * @description A product type controls finance bookings and vat for invoice lines. Each product
         *     type is uniquely identified by its productTypeXid
         */
        ProductType: {
            /**
             * Format: int64
             * @description Identification of the product type. Used on invoice lines
             * @example 123456789
             */
            productTypeXid: number;
            /**
             * @description Name of the product type.
             * @example Salg af ydelser
             */
            typeName: string;
        };
        /** @description A list of products */
        Products: {
            /** @description List of products */
            productList: components["schemas"]["Product"][];
        };
        /**
         * @description A product can (but need not) be applied on lines of outgoing sales invoices.
         *     A product is technically identified by a productXid, but the id intended for presentation
         *     on invoices, etc. is 'productId'
         */
        Product: {
            /**
             * Format: int64
             * @description Technical identification of the product. Used when referencing a product in the API
             * @example 123456789
             */
            productXid: number;
            /**
             * @description Identification of the product for presentation purposes (for humans)
             * @example P2345
             */
            productId?: string;
            /**
             * @description Name of the product
             * @example Subscription, One month
             */
            productName: string;
            /**
             * @description Additional (and optional) extra description
             * @example This covers a one month subscription for the Abc solution
             */
            description?: string;
            /**
             * Format: int64
             * @description Identification of the product type for the product line. It is required for determining finance booking
             *     and application of VAT
             * @example 123456789
             */
            productTypeXid: number;
            /**
             * @description Unit of measure. See list returned by /unitsOfMeasure for valid values
             * @example EA
             */
            unitOfMeasureCode: string;
            /** @description List of prices (different currencies). At present (2026-03), only the first entry is used */
            prices: components["schemas"]["PriceAndCurrency"][];
        };
        /** @description A list of bank postings */
        BankPostings: {
            /** @description List of bank postings */
            bpList: components["schemas"]["BankPosting"][];
        };
        BankPosting: {
            /**
             * Format: int64
             * @description Id reference used by Multi-Regnskab
             * @example 123456789
             */
            xid: number;
            /**
             * @description The date of the bank posting (ISO 8601)
             * @example 2024-12-31
             */
            bankDate: string;
            /**
             * @description The bank text
             * @example Gebyr januar
             */
            bankText: string;
            /**
             * @description The amount
             * @example 197,00
             */
            bankAmount?: string;
            /** @description Extra text supplied by the bank. Typically details about sender or recipient */
            extraBankText?: string;
            /**
             * @description A note text manually entered by the user in Multi-Regnskab
             * @example Samme som altid
             */
            userNote?: string;
            /** @description If available, this should be a unique identifier provided via a PSD2 integration or similar */
            externalRef?: string;
        };
        BankAccounts: {
            accounts?: components["schemas"]["BankAccount"][];
        };
        BankAccount: {
            /**
             * Format: int64
             * @description Id reference used by Multi-Regnskab
             * @example 123456789
             */
            xid: number;
            /**
             * @description Name of the bank account and also the name of associated finance account
             * @example Driftskonto
             */
            name: string;
            /**
             * @description Currency of funds in the account
             * @example DKK
             */
            currency: string;
            /**
             * @description User provided value intended to reflect how the bank identifies the bank account
             * @example 1234 0123456789
             */
            banksIdentification?: string;
        };
        PriceAndCurrency: {
            /**
             * @description A price
             * @example 33,95
             */
            price: string;
            /**
             * @description A currency code (ISO 4217)
             * @example DKK
             */
            currencyCode: string;
        };
        UnitsOfMeasure: {
            /** @description List of units of measure */
            uomList: components["schemas"]["UnitOfMeasure"][];
        };
        UnitOfMeasure: {
            /** @example EA */
            uomCode: string;
            /** @example litre */
            singularis: string;
            /** @example litres */
            pluralis: string;
        };
        /** @enum {string} */
        LanguageCode: "DA" | "EN";
        /** @enum {string} */
        PaymentTermsType: "RUNNING_MONTH" | "NET" | "NET_CASH" | "ALREADY_PAID";
        /** @enum {string} */
        ElectronicInvoiceDestinationType: "DK_GLN" | "DK_CVR" | "DK_PNUMMER" | "DK_SENUMMER" | "PEPPOL";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Authentication data */
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Token information for use in subsequent calls */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Not authorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Refresh token to supplement the access token */
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description Token information for use in subsequent calls */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Not authorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accessRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response with access request code */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessRequestResponse"];
                };
            };
            /** @description Not authorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    invalidateOrExpireTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Specifying what actions to take on the tokens */
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvalidateOrExpireTokensRequest"];
            };
        };
        responses: {
            /** @description Information about the number of tokens affected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidateOrExpireTokensResponse"];
                };
            };
            /** @description Not authorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getBaseUserInformation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Base user information (real name and possibly administrator info) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseUserData"];
                };
            };
            /** @description Not authorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Data required for creating a new user */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Access token data and code that the new user can send to another user in order to be granted access to one or more companies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateUserResponse"];
                };
            };
            /** @description User name already in use */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delete completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of companies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompaniesAndAccess"];
                };
            };
            /** @description Not authorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    archiveFiles: {
        parameters: {
            query: {
                /** @description Company */
                companyXid: number;
                /** @description Max number of lines to be returned */
                maxLines: number;
                /** @description Folder identification */
                folderXid?: number;
                /** @description Continuation token */
                continuationToken?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of archiveFiles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveFiles"];
                };
            };
            /** @description Not authorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    archiveFile: {
        parameters: {
            query: {
                /** @description Company */
                companyXid: number;
                /** @description Identifier of file within company */
                archiveFileXid: number;
                /** @description If this parameter is given a 'true' value, the response will return fileBodyBase64 as an empty string */
                omitFileBody?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archive file data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveFile"];
                };
            };
            /** @description Not authorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateArchiveFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identification of company */
                companyXid: number;
                /** @description Identification of the archive file to delete */
                archiveFileXid: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ArchiveFileUpdate"];
            };
        };
        responses: {
            /** @description Delete completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Archive file not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description This archive file is delete-protected */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteArchiveFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identification of company */
                companyXid: number;
                /** @description Identification of the archive file to delete */
                archiveFileXid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delete completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Archive file not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description This archive file is delete-protected */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    uploadFileForRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["FileUpload"];
            };
        };
        responses: {
            /** @description Identification of the uploaded file to be used in creating registration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityIdentification"];
                };
            };
            /** @description Not authorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createSuggestedRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The data structure to turn into a registration */
        requestBody: {
            content: {
                "application/json": components["schemas"]["Registration"];
            };
        };
        responses: {
            /** @description Identification of the registration created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityIdentification"];
                };
            };
            /** @description Not authorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    customers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identification of company */
                companyXid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of customers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerList"];
                };
            };
            /** @description Not authorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Customer structure. Provide value zero for xid */
        requestBody: {
            content: {
                "application/json": components["schemas"]["Customer"];
            };
        };
        responses: {
            /** @description Identification of the customer created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityIdentification"];
                };
            };
            /** @description Not authorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Invoice structure. Provide zero value for xid */
        requestBody: {
            content: {
                "application/json": components["schemas"]["Invoice"];
            };
        };
        responses: {
            /** @description Identification of the invoice created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityIdentification"];
                };
            };
            /** @description Not authorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createSales: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Sales structure */
        requestBody: {
            content: {
                "application/json": components["schemas"]["SalesRequest"];
            };
        };
        responses: {
            /** @description Identification of the sale and possibly a QR code */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalesResponse"];
                };
            };
            /** @description Not authorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    bankAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identification of company */
                companyXid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of bank accounts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankAccounts"];
                };
            };
            /** @description Not authorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    bankPostings: {
        parameters: {
            query?: {
                /** @description Only return postings from (and including) this date (ISO 8601 format). Defaults to 'one month ago' */
                fromDateIncl?: string;
                /** @description Only return postings until (but including) this date (ISO 8601 format) */
                toDateIncl?: string;
            };
            header?: never;
            path: {
                /** @description Identification of company */
                companyXid: number;
                /** @description Identification of bank account */
                bankAccountXid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of bank postings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankPostings"];
                };
            };
            /** @description Not authorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    bankBalances: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identification of company */
                companyXid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of bank balances */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankBalances"];
                };
            };
            /** @description Not authorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    productTypes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identification of company */
                companyXid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of product types */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductTypes"];
                };
            };
            /** @description Not authorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    products: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identification of company */
                companyXid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of products */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Products"];
                };
            };
            /** @description Not authorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    unitsOfMeasure: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Language - should 'da' or 'en' */
                language: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of units of measure */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitsOfMeasure"];
                };
            };
            /** @description Not authorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
